package nestedTryCatch;

public class Four {
	public static void main(String[] args){ 
		String str = "MUMBAI"; 
		int x[ ] = {0, 1, 2, 3, 4}; 
		
		try{ 
			int slength = str.length(); 
			System.out.println("String length: " +slength);
			
			
			try{ 
				int y = 6; 
				System.out.println(x[y]); // Exception occurred. 
				}catch(Exception ae) // No match is found. 
			{ 
					System.out.println("Exception is thrown"); 
					System.out.println(ae.toString()); 
					} 
			}
		
		catch(Exception npe) // No match is found. 
		{ 
				System.out.println("Exception is thrown "); 
				System.out.println(npe.toString()); 
				} 
		System.out.println("I am out of outer catch block"); 
	
	  } 
	
	}


